server:
  port: 8080

spring:
  application:
    name: cloud-consumer-service
  cloud:
      consul:
        host: 192.169.1.52
        port: 8500
        discovery:
          prefer-ip-address: true
          service-name: ${spring.application.name}
          healthCheckInterval: 15s
          health-check-url: http://192.169.1.165:8006/actuator/health