server:
  port: 8001

spring:
  application:
    name: cloud-payment-service-chenly

# sleuth
  zipkin:
    base-url: http://192.169.1.52:9411
    sleuth:
      sampler:
        #采样率值介于 0 到 1 之间，1 则表示全部采集
        probability: 1




  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.169.1.52:3306/umc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.169.1.165:7001/eureka,http://192.168.1.165:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-secondes: 30
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认为90s),超时将踢出服务
    lease-expiration-duration-in-seconds: 90

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.chenly.springcloud.entities
