server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider

  rabbitmq:
    host: 192.169.1.52
    port: 5672
    username: admin
    password: 123456


  cloud:
    stream:
      binders: #在此处配置要绑定的rabitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          enviroment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.169.1.52
                port: 5672
                username: admin
                password: 123456

      bindings: #服务的整合处理
        output: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的exchange的名称定义
          content-type: application/json #设置消息类型，本次为json ,文本则设置"text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: send-8801
    prefer-ip-address: true #访问路径可以显示ip地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-secondes: 30
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认为90s),超时将踢出服务
    lease-expiration-duration-in-seconds: 90
