server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenlykiko/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
          #
          password: 913011301ao
          username: chenlykiko
          skip-ssl-validation: true
      label: main

  rabbitmq:
    host: 192.169.1.52
    port: 5672
    username: admin
    password: 123456

#服务注册eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'




