server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider-chenly
  cloud:
    nacos:
      discovery:
        server-addr: 192.169.1.82:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'