server:
  port: 8080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://192.169.1.165:7001/eureka,http://192.168.1.165:7002/eureka

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
#指
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
      com.chenly.springcloud.service.PaymentFeignService: debug