server:
  port: 8080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.169.1.165:7001/eureka

feign:
  hystrix:
    enabled: true